import express, { Application, Request, Response } from "express";
import mongoose from "mongoose";
import swaggerUi from "swagger-ui-express";
import { RegisterRoutes } from "./routes/routes"; // Generated by tsoa
import * as swaggerDocument from "../build/swagger.json"; // Generated by tsoa
import getConfig from "./util/config";

// Initialize the application
const app: Application = express();
const config = getConfig();

// Middleware
app.use(express.json());

// Base route
app.get("/", (_req: Request, res: Response) => {
  res.send("Server is running");
});

// Register tsoa routes
RegisterRoutes(app);

// Swagger documentation
app.use("/docs", swaggerUi.serve, swaggerUi.setup(swaggerDocument));

// Start server function
const startServer = async (): Promise<void> => {
  try {
    // Connect to MongoDB
    await mongoose.connect(config.mongoUrl as string);
    console.log("Connected to MongoDB");

    // Start the server
    app.listen(config.port, () => {
      console.log(`Server is running on http://localhost:${config.port}`);
      console.log(
        `Swagger docs available at http://localhost:${config.port}/docs`
      );
    });
  } catch (error) {
    console.error("Failed to start the server:", error);
  }
};

// Execute server startup
startServer();
